python train_deeplabv3plus_new.py \
--eval_dataset cityscapes \
--max_epochs 1 \ # 350 \
--batch_size 8 \
--num_gpus 1 \ # 4 \
--num_workers 16  \
--val_every_n_epochs 1 \ # 3 \
--wandb_group deeplabv3plus_cityscapes \
--exp_name deeplabv3plus_cityscapes_bs8_epoch350 \
--backbone resnet101 \
--lr 0.1  \
--crop_size 768 \
--batch_size 16 \
--output_stride 16 \
--data_root ./data/cityscapes
